### ISSUE TITLE
FuzzyLand slow & unstable

### ISSUE THREAD

**Issue by stefan2904** [LosFuzzys/CTFd#16] opened 2017-05-23 12:36 UTC
After a report from @jowinter and @gwag0,
I just tried to register a test account on FuzzyLand:

* after filling out and submitting the registration form, it is loading forever -> database write issues?
* afterwards, nginx (from the host, not a container) replies with error 500
* (the user is created, but the password does not work)

**Comment by stefan2904** [comment] 2017-05-23 12:36
Maybe this is related to CTFd trying to send mails (with password?), but since `Only allow users with verified emails` is disable, I am not sure. Need to investigate.

**Comment by skogler** [comment] 2017-09-14 12:18
We investigated this issue yesterday. The problem is indeed the email sending, which was not working for TLS connections properly. After a merge from upstream, this should in theory be fixed, but it seems it either was not deployed or the checkbox in the admin interface is not set correctly. Would need admin permissions to test that. Maybe @f0rki or @romanSil can help.

The thing that bugs me though is that this is even happening. This should be triggered in a background thread, and not block the entire web application. Will need to investigate multiprocessing for flask to fix that. Opened issue #17 for that.

**Comment by stefan2904** [comment] 2017-09-17 23:27
* SSL unset, TLS set
* @skogler is an admin in fuzzy.land

**Comment by skogler** [comment] 2017-09-21 18:37
Fixed by setting SSL and updating CTFd.

**Closed by skogler** 2017-09-21 18:37 UTC
Labels: bug
